<!DOCTYPE html>
<html>
<head>
  <title>For You ❤️</title>
</head>
<body style="text-align:center; font-family:Arial; background:#fff0f5; padding:50px;">

  <h1>Hi ❤️</h1>

  <p>This is your private little space 💌</p>

</body>
</html>
